WARNING 2023-10-16 14:18:42,018 django.request Thread-4 22828 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:18:42,029 django.server Thread-4 22828 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17077
WARNING 2023-10-16 14:18:42,177 django.request Thread-3 19908 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:18:42,179 django.server Thread-3 19908 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17077
WARNING 2023-10-16 14:18:42,969 django.request Thread-5 11032 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:18:42,971 django.server Thread-5 11032 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17076
WARNING 2023-10-16 14:18:49,291 django.server Thread-6 8800 basehttp basehttp.py 212 django.server log_message 18632 "GET /static/css/test%20.css HTTP/1.1" 404 1800
WARNING 2023-10-16 14:18:49,807 django.request Thread-5 11032 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:18:49,809 django.server Thread-5 11032 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17076
WARNING 2023-10-16 14:18:50,802 django.request Thread-5 11032 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:18:50,804 django.server Thread-5 11032 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17076
WARNING 2023-10-16 14:19:04,032 django.request Thread-8 15320 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:19:04,046 django.server Thread-8 15320 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17077
WARNING 2023-10-16 14:19:04,997 django.request Thread-8 15320 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:19:04,998 django.server Thread-8 15320 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17076
WARNING 2023-10-16 14:19:06,921 django.request Thread-8 15320 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:19:06,923 django.server Thread-8 15320 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17077
WARNING 2023-10-16 14:19:07,875 django.request Thread-8 15320 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:19:07,876 django.server Thread-8 15320 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17076
WARNING 2023-10-16 14:19:10,030 django.request Thread-8 15320 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:19:10,032 django.server Thread-8 15320 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17076
WARNING 2023-10-16 14:19:10,999 django.request Thread-8 15320 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:19:11,001 django.server Thread-8 15320 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17076
WARNING 2023-10-16 14:19:12,302 django.request Thread-8 15320 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:19:12,303 django.server Thread-8 15320 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17077
WARNING 2023-10-16 14:19:13,312 django.request Thread-9 23164 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:19:13,314 django.server Thread-9 23164 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17076
WARNING 2023-10-16 14:19:14,284 django.server Thread-9 23164 basehttp basehttp.py 212 django.server log_message 18632 "GET /static/css/test%20.css HTTP/1.1" 404 1800
WARNING 2023-10-16 14:19:14,759 django.request Thread-10 15628 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:19:14,764 django.server Thread-10 15628 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17077
WARNING 2023-10-16 14:19:15,682 django.request Thread-10 15628 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:19:15,684 django.server Thread-10 15628 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17076
WARNING 2023-10-16 14:19:16,313 django.request Thread-10 15628 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:19:16,314 django.server Thread-10 15628 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17077
WARNING 2023-10-16 14:19:17,308 django.request Thread-10 15628 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:19:17,310 django.server Thread-10 15628 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17076
WARNING 2023-10-16 17:58:34,895 django.server Thread-1 10228 basehttp basehttp.py 212 django.server log_message 1620 "GET /static/css/test%20.css HTTP/1.1" 404 1800
WARNING 2023-10-16 19:16:43,875 django.request Thread-2 19044 log log.py 241 django.request log_response 12928 Not Found: /favicon.ico
WARNING 2023-10-16 19:16:43,880 django.server Thread-2 19044 basehttp basehttp.py 212 django.server log_message 12928 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-16 19:16:44,997 django.request Thread-2 19044 log log.py 241 django.request log_response 12928 Not Found: /favicon.ico
WARNING 2023-10-16 19:16:44,997 django.server Thread-2 19044 basehttp basehttp.py 212 django.server log_message 12928 "GET /favicon.ico HTTP/1.1" 404 17458
WARNING 2023-10-16 19:17:11,601 django.server Thread-3 21932 basehttp basehttp.py 212 django.server log_message 12928 "GET /static/css/test%20.css HTTP/1.1" 404 1800
WARNING 2023-10-16 19:18:36,492 django.server Thread-9 15324 basehttp basehttp.py 212 django.server log_message 12928 "GET /static/css/test%20.css HTTP/1.1" 404 1800
WARNING 2023-10-17 13:08:27,012 django.server Thread-2 13992 basehttp basehttp.py 212 django.server log_message 14736 "GET /static/css/test%20.css HTTP/1.1" 404 1800
WARNING 2023-10-17 13:08:40,119 django.request Thread-5 8416 log log.py 241 django.request log_response 14736 Not Found: /favicon.ico
WARNING 2023-10-17 13:08:40,119 django.server Thread-5 8416 basehttp basehttp.py 212 django.server log_message 14736 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:08:41,087 django.request Thread-5 8416 log log.py 241 django.request log_response 14736 Not Found: /favicon.ico
WARNING 2023-10-17 13:08:41,089 django.server Thread-5 8416 basehttp basehttp.py 212 django.server log_message 14736 "GET /favicon.ico HTTP/1.1" 404 17458
WARNING 2023-10-17 13:13:18,110 django.server Thread-1 10476 basehttp basehttp.py 212 django.server log_message 7728 "GET /static/css/test%20.css HTTP/1.1" 404 1800
WARNING 2023-10-17 13:13:39,199 django.request Thread-6 8008 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:13:39,201 django.server Thread-6 8008 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:13:40,182 django.request Thread-6 8008 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:13:40,183 django.server Thread-6 8008 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17458
WARNING 2023-10-17 13:13:42,300 django.request Thread-6 8008 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:13:42,300 django.server Thread-6 8008 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:13:43,282 django.request Thread-6 8008 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:13:43,293 django.server Thread-6 8008 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:13:48,735 django.request Thread-10 10568 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:13:48,744 django.server Thread-10 10568 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:13:49,684 django.request Thread-10 10568 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:13:49,688 django.server Thread-10 10568 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17458
WARNING 2023-10-17 13:13:52,004 django.request Thread-13 10144 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:13:52,009 django.server Thread-13 10144 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:13:52,899 django.request Thread-13 10144 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:13:52,899 django.server Thread-13 10144 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17458
WARNING 2023-10-17 13:14:02,869 django.request Thread-14 15808 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:14:02,869 django.server Thread-14 15808 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17458
WARNING 2023-10-17 13:14:04,594 django.request Thread-14 15808 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:14:04,614 django.server Thread-14 15808 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:14:05,504 django.request Thread-14 15808 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:14:05,504 django.server Thread-14 15808 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17458
WARNING 2023-10-17 13:14:08,762 django.request Thread-14 15808 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:14:08,764 django.server Thread-14 15808 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:14:09,705 django.request Thread-14 15808 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:14:09,713 django.server Thread-14 15808 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17458
WARNING 2023-10-17 13:14:11,885 django.request Thread-15 20884 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:14:12,268 django.request Thread-14 15808 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:14:12,278 django.server Thread-14 15808 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:14:13,193 django.request Thread-14 15808 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:14:13,198 django.server Thread-14 15808 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17458
WARNING 2023-10-17 13:14:15,009 django.request Thread-17 6008 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:14:15,578 django.request Thread-16 12356 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:14:15,580 django.server Thread-16 12356 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:14:16,461 django.request Thread-16 12356 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:14:16,464 django.server Thread-16 12356 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17458
WARNING 2023-10-17 13:14:18,792 django.request Thread-16 12356 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:14:18,793 django.server Thread-16 12356 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17458
ERROR 2023-10-17 13:19:11,376 django.request Thread-1 16780 log log.py 241 django.request log_response 8052 Internal Server Error: /admin/assessment/questionset/
Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\options.py", line 681, in get_field
    return self.fields_map[field_name]
KeyError: '__str__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\contrib\admin\utils.py", line 272, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\contrib\admin\utils.py", line 303, in _get_non_gfk_field
    field = opts.get_field(name)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\options.py", line 683, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: QuestionSet has no field named '__str__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\test\utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\test\utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\test\utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 336, in result_list
    "results": list(results(cl)),
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 312, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 303, in __init__
    super().__init__(*items)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 213, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\contrib\admin\utils.py", line 285, in lookup_field
    value = attr()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\models.py", line 30, in __str__
    return f"id:{self.set_id} n_questions:{self.n_questions} is_complited:{self.is_complited} score:{self.score}"#str(self.set_id)
AttributeError: 'QuestionSet' object has no attribute 'is_complited'
ERROR 2023-10-17 13:19:11,529 django.server Thread-1 16780 basehttp basehttp.py 212 django.server log_message 8052 "GET /admin/assessment/questionset/ HTTP/1.1" 500 442566
WARNING 2023-10-17 13:19:13,450 django.request Thread-1 16780 log log.py 241 django.request log_response 8052 Not Found: /favicon.ico
WARNING 2023-10-17 13:19:13,454 django.server Thread-1 16780 basehttp basehttp.py 212 django.server log_message 8052 "GET /favicon.ico HTTP/1.1" 404 17458
WARNING 2023-10-17 13:19:14,533 django.request Thread-1 16780 log log.py 241 django.request log_response 8052 Not Found: /favicon.ico
WARNING 2023-10-17 13:19:14,535 django.server Thread-1 16780 basehttp basehttp.py 212 django.server log_message 8052 "GET /favicon.ico HTTP/1.1" 404 17458
WARNING 2023-10-17 13:19:33,151 django.request Thread-1 15768 log log.py 241 django.request log_response 4892 Not Found: /favicon.ico
WARNING 2023-10-17 13:19:33,153 django.server Thread-1 15768 basehttp basehttp.py 212 django.server log_message 4892 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:19:34,041 django.request Thread-1 15768 log log.py 241 django.request log_response 4892 Not Found: /favicon.ico
WARNING 2023-10-17 13:19:34,043 django.server Thread-1 15768 basehttp basehttp.py 212 django.server log_message 4892 "GET /favicon.ico HTTP/1.1" 404 17458
WARNING 2023-10-17 13:20:13,973 django.request Thread-1 2220 log log.py 241 django.request log_response 5100 Not Found: /favicon.ico
WARNING 2023-10-17 13:20:13,979 django.server Thread-1 2220 basehttp basehttp.py 212 django.server log_message 5100 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:20:14,938 django.request Thread-1 2220 log log.py 241 django.request log_response 5100 Not Found: /favicon.ico
WARNING 2023-10-17 13:20:14,940 django.server Thread-1 2220 basehttp basehttp.py 212 django.server log_message 5100 "GET /favicon.ico HTTP/1.1" 404 17458
WARNING 2023-10-17 13:20:49,538 django.request Thread-1 9560 log log.py 241 django.request log_response 10160 Not Found: /favicon.ico
WARNING 2023-10-17 13:20:49,543 django.server Thread-1 9560 basehttp basehttp.py 212 django.server log_message 10160 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:20:50,503 django.request Thread-3 12460 log log.py 241 django.request log_response 10160 Not Found: /favicon.ico
WARNING 2023-10-17 13:20:50,504 django.server Thread-3 12460 basehttp basehttp.py 212 django.server log_message 10160 "GET /favicon.ico HTTP/1.1" 404 17458
WARNING 2023-10-17 13:21:23,863 django.request Thread-2 15260 log log.py 241 django.request log_response 20096 Not Found: /favicon.ico
WARNING 2023-10-17 13:21:23,868 django.server Thread-2 15260 basehttp basehttp.py 212 django.server log_message 20096 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:21:24,883 django.request Thread-2 15260 log log.py 241 django.request log_response 20096 Not Found: /favicon.ico
WARNING 2023-10-17 13:21:24,885 django.server Thread-2 15260 basehttp basehttp.py 212 django.server log_message 20096 "GET /favicon.ico HTTP/1.1" 404 17458
WARNING 2023-10-17 13:21:48,055 django.request Thread-3 13076 log log.py 241 django.request log_response 20096 Not Found: /favicon.ico
WARNING 2023-10-17 13:21:48,060 django.server Thread-3 13076 basehttp basehttp.py 212 django.server log_message 20096 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:21:48,944 django.request Thread-3 13076 log log.py 241 django.request log_response 20096 Not Found: /favicon.ico
WARNING 2023-10-17 13:21:48,945 django.server Thread-3 13076 basehttp basehttp.py 212 django.server log_message 20096 "GET /favicon.ico HTTP/1.1" 404 17458
WARNING 2023-10-17 13:21:53,260 django.request Thread-4 3044 log log.py 241 django.request log_response 20096 Not Found: /favicon.ico
WARNING 2023-10-17 13:21:53,261 django.server Thread-4 3044 basehttp basehttp.py 212 django.server log_message 20096 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:21:54,195 django.request Thread-4 3044 log log.py 241 django.request log_response 20096 Not Found: /favicon.ico
WARNING 2023-10-17 13:21:54,202 django.server Thread-4 3044 basehttp basehttp.py 212 django.server log_message 20096 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:22:05,360 django.request Thread-5 20484 log log.py 241 django.request log_response 20096 Not Found: /favicon.ico
WARNING 2023-10-17 13:22:05,377 django.server Thread-5 20484 basehttp basehttp.py 212 django.server log_message 20096 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:22:06,226 django.request Thread-5 20484 log log.py 241 django.request log_response 20096 Not Found: /favicon.ico
WARNING 2023-10-17 13:22:06,228 django.server Thread-5 20484 basehttp basehttp.py 212 django.server log_message 20096 "GET /favicon.ico HTTP/1.1" 404 17458
WARNING 2023-10-17 13:22:50,773 django.request Thread-2 13884 log log.py 241 django.request log_response 2644 Not Found: /favicon.ico
WARNING 2023-10-17 13:22:51,263 django.request Thread-1 9972 log log.py 241 django.request log_response 2644 Not Found: /favicon.ico
WARNING 2023-10-17 13:22:51,263 django.server Thread-1 9972 basehttp basehttp.py 212 django.server log_message 2644 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:22:52,205 django.request Thread-1 9972 log log.py 241 django.request log_response 2644 Not Found: /favicon.ico
WARNING 2023-10-17 13:22:52,207 django.server Thread-1 9972 basehttp basehttp.py 212 django.server log_message 2644 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:23:14,957 django.request Thread-1 3240 log log.py 241 django.request log_response 20380 Not Found: /favicon.ico
WARNING 2023-10-17 13:23:14,962 django.server Thread-1 3240 basehttp basehttp.py 212 django.server log_message 20380 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:23:15,866 django.request Thread-1 3240 log log.py 241 django.request log_response 20380 Not Found: /favicon.ico
WARNING 2023-10-17 13:23:15,869 django.server Thread-1 3240 basehttp basehttp.py 212 django.server log_message 20380 "GET /favicon.ico HTTP/1.1" 404 17458
WARNING 2023-10-17 13:24:01,429 django.request Thread-1 1976 log log.py 241 django.request log_response 14568 Not Found: /favicon.ico
WARNING 2023-10-17 13:24:01,438 django.server Thread-1 1976 basehttp basehttp.py 212 django.server log_message 14568 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:24:02,358 django.request Thread-1 1976 log log.py 241 django.request log_response 14568 Not Found: /favicon.ico
WARNING 2023-10-17 13:24:02,358 django.server Thread-1 1976 basehttp basehttp.py 212 django.server log_message 14568 "GET /favicon.ico HTTP/1.1" 404 17458
WARNING 2023-10-17 13:24:03,233 django.request Thread-1 1976 log log.py 241 django.request log_response 14568 Not Found: /favicon.ico
WARNING 2023-10-17 13:24:03,233 django.server Thread-1 1976 basehttp basehttp.py 212 django.server log_message 14568 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:24:04,137 django.request Thread-1 1976 log log.py 241 django.request log_response 14568 Not Found: /favicon.ico
WARNING 2023-10-17 13:24:04,140 django.server Thread-1 1976 basehttp basehttp.py 212 django.server log_message 14568 "GET /favicon.ico HTTP/1.1" 404 17458
WARNING 2023-10-17 13:24:56,764 django.request Thread-1 11404 log log.py 241 django.request log_response 21100 Not Found: /favicon.ico
WARNING 2023-10-17 13:24:56,766 django.server Thread-1 11404 basehttp basehttp.py 212 django.server log_message 21100 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:24:57,679 django.request Thread-1 11404 log log.py 241 django.request log_response 21100 Not Found: /favicon.ico
WARNING 2023-10-17 13:24:57,680 django.server Thread-1 11404 basehttp basehttp.py 212 django.server log_message 21100 "GET /favicon.ico HTTP/1.1" 404 17459
ERROR 2023-10-17 14:29:04,074 django.request Thread-2 1056 log log.py 241 django.request log_response 21968 Internal Server Error: /admin_report/
Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\fields\__init__.py", line 2053, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\views.py", line 361, in admin_test_report
    scores_list.append(QuestionSet.objects.filter(score=score).count())
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1318, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\fields\__init__.py", line 2055, in get_prep_value
    raise e.__class__(
TypeError: Field 'score' expected a number but got {'score': 3}.
ERROR 2023-10-17 14:29:04,267 django.server Thread-2 1056 basehttp basehttp.py 212 django.server log_message 21968 "GET /admin_report/ HTTP/1.1" 500 149360
WARNING 2023-10-17 14:29:05,704 django.request Thread-2 1056 log log.py 241 django.request log_response 21968 Not Found: /favicon.ico
WARNING 2023-10-17 14:29:05,706 django.server Thread-2 1056 basehttp basehttp.py 212 django.server log_message 21968 "GET /favicon.ico HTTP/1.1" 404 17634
WARNING 2023-10-17 14:29:06,941 django.request Thread-2 1056 log log.py 241 django.request log_response 21968 Not Found: /favicon.ico
WARNING 2023-10-17 14:29:06,942 django.server Thread-2 1056 basehttp basehttp.py 212 django.server log_message 21968 "GET /favicon.ico HTTP/1.1" 404 17634
ERROR 2023-10-17 14:29:37,003 django.request Thread-1 10828 log log.py 241 django.request log_response 21792 Internal Server Error: /admin_report/
Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\fields\__init__.py", line 2053, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\views.py", line 361, in admin_test_report
    scores_list.append(QuestionSet.objects.filter(score=score).count())
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1318, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\fields\__init__.py", line 2055, in get_prep_value
    raise e.__class__(
TypeError: Field 'score' expected a number but got {'score': 3}.
ERROR 2023-10-17 14:29:37,160 django.server Thread-1 10828 basehttp basehttp.py 212 django.server log_message 21792 "GET /admin_report/ HTTP/1.1" 500 149359
WARNING 2023-10-17 14:29:37,694 django.request Thread-1 10828 log log.py 241 django.request log_response 21792 Not Found: /favicon.ico
WARNING 2023-10-17 14:29:37,694 django.server Thread-1 10828 basehttp basehttp.py 212 django.server log_message 21792 "GET /favicon.ico HTTP/1.1" 404 17634
WARNING 2023-10-17 14:29:38,645 django.request Thread-1 10828 log log.py 241 django.request log_response 21792 Not Found: /favicon.ico
WARNING 2023-10-17 14:29:38,645 django.server Thread-1 10828 basehttp basehttp.py 212 django.server log_message 21792 "GET /favicon.ico HTTP/1.1" 404 17633
ERROR 2023-10-17 14:29:51,730 django.request Thread-1 2984 log log.py 241 django.request log_response 3348 Internal Server Error: /admin_report/
Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\fields\__init__.py", line 2053, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\views.py", line 361, in admin_test_report
    scores_list.append(QuestionSet.objects.filter(score=score).count())
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1318, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\fields\__init__.py", line 2055, in get_prep_value
    raise e.__class__(
TypeError: Field 'score' expected a number but got {'score': 3}.
ERROR 2023-10-17 14:29:51,752 django.request Thread-2 21688 log log.py 241 django.request log_response 3348 Internal Server Error: /admin_report/
Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\fields\__init__.py", line 2053, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\views.py", line 361, in admin_test_report
    scores_list.append(QuestionSet.objects.filter(score=score).count())
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1318, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\fields\__init__.py", line 2055, in get_prep_value
    raise e.__class__(
TypeError: Field 'score' expected a number but got {'score': 3}.
ERROR 2023-10-17 14:29:52,114 django.server Thread-2 21688 basehttp basehttp.py 212 django.server log_message 3348 "GET /admin_report/ HTTP/1.1" 500 149360
WARNING 2023-10-17 14:29:53,800 django.request Thread-2 21688 log log.py 241 django.request log_response 3348 Not Found: /favicon.ico
WARNING 2023-10-17 14:29:53,802 django.server Thread-2 21688 basehttp basehttp.py 212 django.server log_message 3348 "GET /favicon.ico HTTP/1.1" 404 17634
WARNING 2023-10-17 14:29:54,855 django.request Thread-2 21688 log log.py 241 django.request log_response 3348 Not Found: /favicon.ico
WARNING 2023-10-17 14:29:54,855 django.server Thread-2 21688 basehttp basehttp.py 212 django.server log_message 3348 "GET /favicon.ico HTTP/1.1" 404 17633
ERROR 2023-10-17 14:31:48,960 django.request Thread-2 12120 log log.py 241 django.request log_response 8004 Internal Server Error: /report/
Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py", line 208, in admin_report
    x=[set.score['score'] for set in sets],
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py", line 208, in <listcomp>
    x=[set.score['score'] for set in sets],
TypeError: 'int' object is not subscriptable
ERROR 2023-10-17 14:31:49,147 django.server Thread-2 12120 basehttp basehttp.py 212 django.server log_message 8004 "GET /report/ HTTP/1.1" 500 90101
WARNING 2023-10-17 14:31:49,984 django.request Thread-2 12120 log log.py 241 django.request log_response 8004 Not Found: /favicon.ico
WARNING 2023-10-17 14:31:49,986 django.server Thread-2 12120 basehttp basehttp.py 212 django.server log_message 8004 "GET /favicon.ico HTTP/1.1" 404 17634
WARNING 2023-10-17 14:31:50,917 django.request Thread-2 12120 log log.py 241 django.request log_response 8004 Not Found: /favicon.ico
WARNING 2023-10-17 14:31:50,944 django.server Thread-2 12120 basehttp basehttp.py 212 django.server log_message 8004 "GET /favicon.ico HTTP/1.1" 404 17633
ERROR 2023-10-17 14:44:10,313 django.request Thread-1 5748 log log.py 241 django.request log_response 18456 Internal Server Error: /report/
Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py", line 211, in admin_report
    text=[set.username for set in sets],
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py", line 211, in <listcomp>
    text=[set.username for set in sets],
AttributeError: 'QuestionSet' object has no attribute 'username'
ERROR 2023-10-17 14:44:10,446 django.server Thread-1 5748 basehttp basehttp.py 212 django.server log_message 18456 "GET /report/ HTTP/1.1" 500 90584
WARNING 2023-10-17 14:44:10,996 django.request Thread-1 5748 log log.py 241 django.request log_response 18456 Not Found: /favicon.ico
WARNING 2023-10-17 14:44:10,996 django.server Thread-1 5748 basehttp basehttp.py 212 django.server log_message 18456 "GET /favicon.ico HTTP/1.1" 404 17634
WARNING 2023-10-17 14:44:11,946 django.request Thread-1 5748 log log.py 241 django.request log_response 18456 Not Found: /favicon.ico
WARNING 2023-10-17 14:44:11,946 django.server Thread-1 5748 basehttp basehttp.py 212 django.server log_message 18456 "GET /favicon.ico HTTP/1.1" 404 17633
ERROR 2023-10-17 14:44:43,264 django.request Thread-1 12676 log log.py 241 django.request log_response 15700 Internal Server Error: /report/
Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py", line 217, in admin_report
    chart = fig.to_html()#full_html=False, include_plotlyjs=False
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\plotly\basedatatypes.py", line 3604, in to_html
    return pio.to_html(self, *args, **kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\plotly\io\_html.py", line 144, in to_html
    jdata = to_json_plotly(fig_dict.get("data", []))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\plotly\io\_json.py", line 143, in to_json_plotly
    json.dumps(plotly_object, cls=PlotlyJSONEncoder, **opts), _swap_json
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\_plotly_utils\utils.py", line 59, in encode
    encoded_o = super(PlotlyJSONEncoder, self).encode(o)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\_plotly_utils\utils.py", line 136, in default
    return _json.JSONEncoder.default(self, obj)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type User is not JSON serializable
ERROR 2023-10-17 14:44:43,434 django.server Thread-1 12676 basehttp basehttp.py 212 django.server log_message 15700 "GET /report/ HTTP/1.1" 500 145601
WARNING 2023-10-17 14:44:43,933 django.request Thread-1 12676 log log.py 241 django.request log_response 15700 Not Found: /favicon.ico
WARNING 2023-10-17 14:44:43,933 django.server Thread-1 12676 basehttp basehttp.py 212 django.server log_message 15700 "GET /favicon.ico HTTP/1.1" 404 17634
WARNING 2023-10-17 14:44:44,941 django.request Thread-1 12676 log log.py 241 django.request log_response 15700 Not Found: /favicon.ico
WARNING 2023-10-17 14:44:44,957 django.server Thread-1 12676 basehttp basehttp.py 212 django.server log_message 15700 "GET /favicon.ico HTTP/1.1" 404 17633
ERROR 2023-10-17 14:50:22,479 django.request Thread-1 16608 log log.py 241 django.request log_response 15932 Internal Server Error: /report/
Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py", line 217, in admin_report
    return render(request, 'report.html', context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\test\utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\test\utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader_tags.py", line 208, in render
    return template.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 177, in render
    return self._render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\test\utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'report' not found. 'report' is not a valid view function or pattern name.
ERROR 2023-10-17 14:50:23,047 django.server Thread-1 16608 basehttp basehttp.py 212 django.server log_message 15932 "GET /report/ HTTP/1.1" 500 383611
WARNING 2023-10-17 14:50:24,308 django.request Thread-2 14356 log log.py 241 django.request log_response 15932 Not Found: /favicon.ico
WARNING 2023-10-17 14:50:24,328 django.server Thread-2 14356 basehttp basehttp.py 212 django.server log_message 15932 "GET /favicon.ico HTTP/1.1" 404 17634
WARNING 2023-10-17 14:50:25,263 django.request Thread-2 14356 log log.py 241 django.request log_response 15932 Not Found: /favicon.ico
WARNING 2023-10-17 14:50:25,264 django.server Thread-2 14356 basehttp basehttp.py 212 django.server log_message 15932 "GET /favicon.ico HTTP/1.1" 404 17633
ERROR 2023-10-17 14:50:31,953 django.request Thread-2 14356 log log.py 241 django.request log_response 15932 Internal Server Error: /report/
Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py", line 217, in admin_report
    return render(request, 'report.html', context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\test\utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\test\utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader_tags.py", line 208, in render
    return template.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 177, in render
    return self._render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\test\utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'report' not found. 'report' is not a valid view function or pattern name.
ERROR 2023-10-17 14:50:32,127 django.server Thread-2 14356 basehttp basehttp.py 212 django.server log_message 15932 "GET /report/ HTTP/1.1" 500 383611
WARNING 2023-10-17 14:50:33,155 django.request Thread-2 14356 log log.py 241 django.request log_response 15932 Not Found: /favicon.ico
WARNING 2023-10-17 14:50:33,157 django.server Thread-2 14356 basehttp basehttp.py 212 django.server log_message 15932 "GET /favicon.ico HTTP/1.1" 404 17634
WARNING 2023-10-17 14:50:34,086 django.request Thread-2 14356 log log.py 241 django.request log_response 15932 Not Found: /favicon.ico
WARNING 2023-10-17 14:50:34,086 django.server Thread-2 14356 basehttp basehttp.py 212 django.server log_message 15932 "GET /favicon.ico HTTP/1.1" 404 17634
WARNING 2023-10-17 14:54:35,640 django.server Thread-4 6648 basehttp basehttp.py 212 django.server log_message 3488 "GET /static/css/test%20.css HTTP/1.1" 404 1800
WARNING 2023-10-17 14:54:44,557 django.request Thread-8 17672 log log.py 241 django.request log_response 3488 Not Found: /favicon.ico
WARNING 2023-10-17 14:54:44,559 django.server Thread-8 17672 basehttp basehttp.py 212 django.server log_message 3488 "GET /favicon.ico HTTP/1.1" 404 17637
WARNING 2023-10-17 14:54:45,545 django.request Thread-8 17672 log log.py 241 django.request log_response 3488 Not Found: /favicon.ico
WARNING 2023-10-17 14:54:45,545 django.server Thread-8 17672 basehttp basehttp.py 212 django.server log_message 3488 "GET /favicon.ico HTTP/1.1" 404 17636
WARNING 2023-10-17 15:28:50,533 django.server Thread-4 15932 basehttp basehttp.py 212 django.server log_message 14584 "GET /static/css/test%20.css HTTP/1.1" 404 1800
ERROR 2023-10-17 15:28:57,393 django.request Thread-3 17000 log log.py 241 django.request log_response 14584 Internal Server Error: /report/
Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py", line 220, in admin_report
    fig.update_layout(title={
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\plotly\graph_objs\_figure.py", line 775, in update_layout
    return super(Figure, self).update_layout(dict1, overwrite, **kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\plotly\basedatatypes.py", line 1393, in update_layout
    self.layout.update(dict1, overwrite=overwrite, **kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\plotly\basedatatypes.py", line 5139, in update
    BaseFigure._perform_update(self, kwargs, overwrite=overwrite)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\plotly\basedatatypes.py", line 3921, in _perform_update
    BaseFigure._perform_update(plotly_obj[key], val)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\plotly\basedatatypes.py", line 3915, in _perform_update
    validator = plotly_obj._get_prop_validator(key)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\plotly\basedatatypes.py", line 4634, in _get_prop_validator
    return plotly_obj._get_validator(prop)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\plotly\basedatatypes.py", line 4346, in _get_validator
    return ValidatorCache.get_validator(self._path_str, prop)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\plotly\validator_cache.py", line 28, in get_validator
    validator = getattr(
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\_plotly_utils\importers.py", line 39, in __getattr__
    raise AttributeError(
AttributeError: module 'plotly.validators.layout.title' has no attribute 'Font-SizeValidator'
ERROR 2023-10-17 15:28:57,555 django.server Thread-3 17000 basehttp basehttp.py 212 django.server log_message 14584 "GET /report/ HTTP/1.1" 500 133908
WARNING 2023-10-17 15:28:58,420 django.request Thread-3 17000 log log.py 241 django.request log_response 14584 Not Found: /favicon.ico
WARNING 2023-10-17 15:28:58,422 django.server Thread-3 17000 basehttp basehttp.py 212 django.server log_message 14584 "GET /favicon.ico HTTP/1.1" 404 17637
WARNING 2023-10-17 15:28:59,410 django.request Thread-3 17000 log log.py 241 django.request log_response 14584 Not Found: /favicon.ico
WARNING 2023-10-17 15:28:59,413 django.server Thread-3 17000 basehttp basehttp.py 212 django.server log_message 14584 "GET /favicon.ico HTTP/1.1" 404 17636
ERROR 2023-10-17 15:30:50,997 django.request Thread-1 22324 log log.py 241 django.request log_response 3596 Internal Server Error: /report/
Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py", line 229, in admin_report
    return render(request, 'report.html', context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\defaulttags.py", line 1372, in url
    viewname = parser.compile_filter(bits[1])
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''chart' from ''chart'
ERROR 2023-10-17 15:30:51,229 django.server Thread-1 22324 basehttp basehttp.py 212 django.server log_message 3596 "GET /report/ HTTP/1.1" 500 237979
WARNING 2023-10-17 15:30:52,306 django.request Thread-1 22324 log log.py 241 django.request log_response 3596 Not Found: /favicon.ico
WARNING 2023-10-17 15:30:52,452 django.server Thread-1 22324 basehttp basehttp.py 212 django.server log_message 3596 "GET /favicon.ico HTTP/1.1" 404 17637
WARNING 2023-10-17 15:30:53,414 django.request Thread-1 22324 log log.py 241 django.request log_response 3596 Not Found: /favicon.ico
WARNING 2023-10-17 15:30:53,421 django.server Thread-1 22324 basehttp basehttp.py 212 django.server log_message 3596 "GET /favicon.ico HTTP/1.1" 404 17637
ERROR 2023-10-17 15:31:28,673 django.request Thread-3 8068 log log.py 241 django.request log_response 3596 Internal Server Error: /report/
Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py", line 229, in admin_report
    return render(request, 'report.html', context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\defaulttags.py", line 1372, in url
    viewname = parser.compile_filter(bits[1])
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''admin_report' from ''admin_report'
ERROR 2023-10-17 15:31:28,766 django.server Thread-3 8068 basehttp basehttp.py 212 django.server log_message 3596 "GET /report/ HTTP/1.1" 500 238148
WARNING 2023-10-17 15:31:29,275 django.request Thread-3 8068 log log.py 241 django.request log_response 3596 Not Found: /favicon.ico
WARNING 2023-10-17 15:31:29,276 django.server Thread-3 8068 basehttp basehttp.py 212 django.server log_message 3596 "GET /favicon.ico HTTP/1.1" 404 17637
WARNING 2023-10-17 15:31:30,327 django.request Thread-3 8068 log log.py 241 django.request log_response 3596 Not Found: /favicon.ico
WARNING 2023-10-17 15:31:30,329 django.server Thread-3 8068 basehttp basehttp.py 212 django.server log_message 3596 "GET /favicon.ico HTTP/1.1" 404 17637
ERROR 2023-10-17 15:32:07,963 django.request Thread-1 2752 log log.py 241 django.request log_response 11432 Internal Server Error: /report/
Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py", line 229, in admin_report
    return render(request, 'report.html', context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\defaulttags.py", line 1372, in url
    viewname = parser.compile_filter(bits[1])
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''admin_report' from ''admin_report'
ERROR 2023-10-17 15:32:08,273 django.server Thread-1 2752 basehttp basehttp.py 212 django.server log_message 11432 "GET /report/ HTTP/1.1" 500 238148
WARNING 2023-10-17 15:32:09,090 django.request Thread-1 2752 log log.py 241 django.request log_response 11432 Not Found: /favicon.ico
WARNING 2023-10-17 15:32:09,132 django.server Thread-1 2752 basehttp basehttp.py 212 django.server log_message 11432 "GET /favicon.ico HTTP/1.1" 404 17637
WARNING 2023-10-17 15:32:10,079 django.request Thread-1 2752 log log.py 241 django.request log_response 11432 Not Found: /favicon.ico
WARNING 2023-10-17 15:32:10,081 django.server Thread-1 2752 basehttp basehttp.py 212 django.server log_message 11432 "GET /favicon.ico HTTP/1.1" 404 17636
ERROR 2023-10-17 15:34:27,717 django.request Thread-2 17236 log log.py 241 django.request log_response 11432 Internal Server Error: /report/
Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py", line 229, in admin_report
    return render(request, 'report.html', context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\defaulttags.py", line 1372, in url
    viewname = parser.compile_filter(bits[1])
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''admin_report' from ''admin_report'
ERROR 2023-10-17 15:34:27,803 django.server Thread-2 17236 basehttp basehttp.py 212 django.server log_message 11432 "GET /report/ HTTP/1.1" 500 238147
WARNING 2023-10-17 15:34:28,358 django.request Thread-3 18732 log log.py 241 django.request log_response 11432 Not Found: /favicon.ico
WARNING 2023-10-17 15:34:28,359 django.server Thread-3 18732 basehttp basehttp.py 212 django.server log_message 11432 "GET /favicon.ico HTTP/1.1" 404 17637
WARNING 2023-10-17 15:34:29,385 django.request Thread-3 18732 log log.py 241 django.request log_response 11432 Not Found: /favicon.ico
WARNING 2023-10-17 15:34:29,386 django.server Thread-3 18732 basehttp basehttp.py 212 django.server log_message 11432 "GET /favicon.ico HTTP/1.1" 404 17636
WARNING 2023-10-17 15:35:19,255 django.request Thread-1 20484 log log.py 241 django.request log_response 21644 Not Found: /report/
WARNING 2023-10-17 15:35:19,256 django.server Thread-1 20484 basehttp basehttp.py 212 django.server log_message 21644 "GET /report/ HTTP/1.1" 404 17627
WARNING 2023-10-17 15:35:19,761 django.request Thread-1 20484 log log.py 241 django.request log_response 21644 Not Found: /favicon.ico
WARNING 2023-10-17 15:35:19,762 django.server Thread-1 20484 basehttp basehttp.py 212 django.server log_message 21644 "GET /favicon.ico HTTP/1.1" 404 17643
WARNING 2023-10-17 15:35:20,808 django.request Thread-1 20484 log log.py 241 django.request log_response 21644 Not Found: /favicon.ico
WARNING 2023-10-17 15:35:20,809 django.server Thread-1 20484 basehttp basehttp.py 212 django.server log_message 21644 "GET /favicon.ico HTTP/1.1" 404 17643
ERROR 2023-10-17 15:35:27,964 django.request Thread-1 20484 log log.py 241 django.request log_response 21644 Internal Server Error: /admin_report/
Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py", line 229, in admin_report
    return render(request, 'report.html', context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: report.html
ERROR 2023-10-17 15:35:28,164 django.server Thread-1 20484 basehttp basehttp.py 212 django.server log_message 21644 "GET /admin_report/ HTTP/1.1" 500 126234
WARNING 2023-10-17 15:35:28,978 django.request Thread-1 20484 log log.py 241 django.request log_response 21644 Not Found: /favicon.ico
WARNING 2023-10-17 15:35:28,980 django.server Thread-1 20484 basehttp basehttp.py 212 django.server log_message 21644 "GET /favicon.ico HTTP/1.1" 404 17643
WARNING 2023-10-17 15:35:29,886 django.request Thread-1 20484 log log.py 241 django.request log_response 21644 Not Found: /favicon.ico
WARNING 2023-10-17 15:35:29,888 django.server Thread-1 20484 basehttp basehttp.py 212 django.server log_message 21644 "GET /favicon.ico HTTP/1.1" 404 17643
ERROR 2023-10-17 15:35:32,880 django.request Thread-1 20484 log log.py 241 django.request log_response 21644 Internal Server Error: /admin_report/
Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py", line 229, in admin_report
    return render(request, 'report.html', context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: report.html
ERROR 2023-10-17 15:35:32,955 django.server Thread-1 20484 basehttp basehttp.py 212 django.server log_message 21644 "GET /admin_report/ HTTP/1.1" 500 126371
WARNING 2023-10-17 15:35:33,494 django.request Thread-1 20484 log log.py 241 django.request log_response 21644 Not Found: /favicon.ico
WARNING 2023-10-17 15:35:33,496 django.server Thread-1 20484 basehttp basehttp.py 212 django.server log_message 21644 "GET /favicon.ico HTTP/1.1" 404 17643
WARNING 2023-10-17 15:35:34,513 django.request Thread-1 20484 log log.py 241 django.request log_response 21644 Not Found: /favicon.ico
WARNING 2023-10-17 15:35:34,516 django.server Thread-1 20484 basehttp basehttp.py 212 django.server log_message 21644 "GET /favicon.ico HTTP/1.1" 404 17642
ERROR 2023-10-17 15:35:52,021 django.request Thread-1 11132 log log.py 241 django.request log_response 20868 Internal Server Error: /admin_report/
Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py", line 229, in admin_report
    return render(request, 'admin_report.html', context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\defaulttags.py", line 1372, in url
    viewname = parser.compile_filter(bits[1])
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''admin_report' from ''admin_report'
ERROR 2023-10-17 15:35:52,217 django.server Thread-1 11132 basehttp basehttp.py 212 django.server log_message 20868 "GET /admin_report/ HTTP/1.1" 500 238166
WARNING 2023-10-17 15:35:53,325 django.request Thread-1 11132 log log.py 241 django.request log_response 20868 Not Found: /favicon.ico
WARNING 2023-10-17 15:35:53,327 django.server Thread-1 11132 basehttp basehttp.py 212 django.server log_message 20868 "GET /favicon.ico HTTP/1.1" 404 17642
WARNING 2023-10-17 15:35:54,460 django.request Thread-1 11132 log log.py 241 django.request log_response 20868 Not Found: /favicon.ico
WARNING 2023-10-17 15:35:54,461 django.server Thread-1 11132 basehttp basehttp.py 212 django.server log_message 20868 "GET /favicon.ico HTTP/1.1" 404 17643
ERROR 2023-10-17 15:35:57,839 django.request Thread-1 11132 log log.py 241 django.request log_response 20868 Internal Server Error: /admin_report/
Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py", line 229, in admin_report
    return render(request, 'admin_report.html', context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\defaulttags.py", line 1372, in url
    viewname = parser.compile_filter(bits[1])
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''admin_report' from ''admin_report'
ERROR 2023-10-17 15:35:58,044 django.server Thread-1 11132 basehttp basehttp.py 212 django.server log_message 20868 "GET /admin_report/ HTTP/1.1" 500 238166
WARNING 2023-10-17 15:35:58,794 django.request Thread-1 11132 log log.py 241 django.request log_response 20868 Not Found: /favicon.ico
WARNING 2023-10-17 15:35:58,796 django.server Thread-1 11132 basehttp basehttp.py 212 django.server log_message 20868 "GET /favicon.ico HTTP/1.1" 404 17643
WARNING 2023-10-17 15:35:59,809 django.request Thread-1 11132 log log.py 241 django.request log_response 20868 Not Found: /favicon.ico
WARNING 2023-10-17 15:35:59,810 django.server Thread-1 11132 basehttp basehttp.py 212 django.server log_message 20868 "GET /favicon.ico HTTP/1.1" 404 17642
